### ISSUE TITLE
analyzer plugin alternative

### ISSUE THREAD

**Issue by radzish** [angulardart/angular#1935]
I was trying to upgrade angular from 6.0.0-alpha to 6.0.1 and noticed that new version is missing angular analyzer plugin: IntellyJ IDEA autocomplete stopped working in templates.

I did something wrong or this functionality is just removed and discontinued. Are there alternatives or workarounds ?

**Comment by lejard-h** [comment]
Last release discontinued the analyzer plugin and also removed it I guess (never worked for me anyway).
I don't think there is a workaround.

I know you are on IntelliJ but @aadarshadhakalg started a VSCode extension for Angular dart a few weeks ago, mostly containing snippets at the moment 
But I am trying to improve it by adding follow Template link and selector on click, and hopefully autocomplete feature inside template.

**Comment by radzish** [comment]
Ok, then I will keep 6.0.0-alpha, as for me productivity is quite important. Now sure why plugin did not work for you - it does job for me and I noticed that it is missing right after I upgraded.
VSCode thing is cool, but I invested in Idea quite a lot of my experience and money, so switching to VSCode is not an option for me either.

**Comment by insinfo** [comment]
@lejard-h 
congratulations I am happy to know that someone is working on an extension for the AngularDart template, I have been working a lot on many angularDart projects I love angularDart; I also published packages for angularDart such as https://pub.dev/packages/essential_components, https://pub.dev/packages/essential_xlsx, https://pub.dev/packages/essential_rest, https: // pub. dev / packages / fluent_query_builder.
> But I am trying to improve...

**Comment by insinfo** [comment]
@radzish
the plugin worked for me too, the link is broken
https://github.com/angulardart/angular/tree/master/angular_analyzer_plugin

**Comment by insinfo** [comment]
@lejard-h 
I opened a problem in the repository because it is not working with vs code 1.45.1
https://github.com/aadarshadhakalg/ADSnippets/issues/8

**Comment by kevmoo** [comment]
We have no plans to update the analyzer plugin.

**Comment by insinfo** [comment]
This is bad news as it would be a good productivity tool. but if this is for more focus on the core AngularDart packages, the analyzer plugin can be left out as it is not so necessary.
