### ISSUE TITLE
Can't work together with grpc-dart-web

### ISSUE THREAD

**Issue by heihuhu310** [angulardart/angular#1958]
Hi, I want to use AngularDart with gRPC-dart-web for web application, but I found the library crypto they dependency is not incompatible:

AngularDart 6.0.0.1 require crypto ^2.0.0 from analyzer >=0.39.5 <0.41.2
gRPC-dart-web(gRPC 3.0.0 in pub.dev) require crypto ^3.0.0

Dart SDK Version:
Dart SDK version: 2.12.2 (stable) (Wed Mar 17 10:30:20 2021 +0100) on "macos_x64"
AngularDart Version:
6.0.0.1
Platform: MacOS X
Browser: Chrome

Thank you!

**Comment by Reductions** [comment]
Try using grpc version 2.9.0.

**Comment by matehat** [comment]
AngularDart 6.0.1 seems to [depend on analyzer ^1.0.0](https://github.com/angulardart/angular/blob/master/angular/pubspec.yaml#L21) though.

**Comment by Reductions** [comment]
> AngularDart 6.0.1 seems to [depend on analyzer ^1.0.0](https://github.com/angulardart/angular/blob/1334162e94c0c3521e6c4daaa49de9266aefa0e2/angular/pubspec.yaml#L21) though, which [depends on crypto ^3.0.0](https://github.com/dart-lang/sdk/commit/1faa9f0f8c931d1ead0eb6827f60ef63cedf9679#diff-a8403f1fc69a35a5ee70b920d57c1d402b06e5d10929ec8daedfebbf8c34c42fR15)

Not true. Angular 6.0.1 depends on analyzer version 0.40.0. What you see there is the master branch that contains an effort to migrate to NNBD.

**Comment by matehat** [comment]
Ah! Good catch

**Comment by heihuhu310** [comment]
@Reductions Thank you so much, AngularDart 6.0.1 can work togther with gRPC 2.9.0 for web application.
