### ISSUE TITLE
Depends on outdated build versions

### ISSUE THREAD

**Issue by pavll** [angulardart/angular#1961]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* [2.12.4] Dart SDK Version (`dart --version`)
* [6.0.1 ] AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`)
* [build_runner, build_test, build_web_compilers] Any other packages or constraints we should know about

AngularDart is incompatible with the newest stable versions of the packages mentioned above. Please upgrade to the latest because the current versions are outdated, for example: build_runner added Null safety in 2.0.0 and above but it's not possible to use it because the dependencies of angular doesn't allow this

**Comment by pavll** [comment]
I've just recognized that this project is dead

**Comment by lejard-h** [comment]
Lol, it's not, they are working on it here https://github.com/angulardart/angular/tree/google

It's not a simple dependency upgrade...
